apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capital-simulator

resources:
  - namespace.yaml
  - infra/mongo.yaml
  - infra/redis.yaml
  - services/api-gateway.yaml
  - services/commodity-service.yaml
  - services/agent-service.yaml
  - services/market-service.yaml
  - services/simulation-engine.yaml
  - services/finance-service.yaml
  - services/web.yaml

commonLabels:
  app.kubernetes.io/part-of: capital-simulator
