// illusions.go — Vol. III Ch. 50 types: Illusions Created by Competition.
// Competition (market prices, buying and selling) generates systematic illusions
// that hide the origin of value in production. Cost-price (c+v) appears to the
// individual capitalist as the "real value" of the commodity, and profit appears
// to arise in the sale rather than from surplus-labour. At the social level, the
// annual revenue is v+s (new value); the constant capital c appears to reproduce
// itself automatically through exchange between departments.
package revenue

import "time"

// CompetitionIllusionID identifies a competition-illusion record.
type CompetitionIllusionID string

// NewCompetitionIllusionID returns a fresh 96-bit hex ID.
func NewCompetitionIllusionID() CompetitionIllusionID {
	return CompetitionIllusionID(newID())
}

// CompetitionIllusion records one false appearance generated by market competition,
// contrasting its surface appearance with the real relation, and naming the sphere
// of competition that produces it.
type CompetitionIllusion struct {
	ID                CompetitionIllusionID `json:"id"`
	Name              string                `json:"name"`
	SurfaceAppearance string                `json:"surface_appearance"`
	RealRelation      string                `json:"real_relation"`
	ProducedBy        string                `json:"produced_by"`
	CreatedAt         time.Time             `json:"created_at"`
}

// CostPriceFetishID identifies a cost-price-fetish record.
type CostPriceFetishID string

// NewCostPriceFetishID returns a fresh 96-bit hex ID.
func NewCostPriceFetishID() CostPriceFetishID {
	return CostPriceFetishID(newID())
}

// CostPriceFetish records the individual capitalist's view: cost-price (c+v) appears
// as the commodity's "real value", and profit appears as an addition made in exchange.
// CostPriceBP = c + v; ActualValueBP = cost-price + profit (= c + v + s).
type CostPriceFetish struct {
	ID                CostPriceFetishID `json:"id"`
	ConstantCapitalBP int64             `json:"constant_capital_bp"`
	VariableCapitalBP int64             `json:"variable_capital_bp"`
	CostPriceBP       int64             `json:"cost_price_bp"`
	ProfitBP          int64             `json:"profit_bp"`
	ActualValueBP     int64             `json:"actual_value_bp"`
	CreatedAt         time.Time         `json:"created_at"`
}

// AnnualRevenueAccountID identifies an annual-revenue-account record.
type AnnualRevenueAccountID string

// NewAnnualRevenueAccountID returns a fresh 96-bit hex ID.
func NewAnnualRevenueAccountID() AnnualRevenueAccountID {
	return AnnualRevenueAccountID(newID())
}

// AnnualRevenueAccount is the society-wide accounting that competition obscures:
// new value (v+s) is the total distributable revenue (wages + profit-and-rent),
// while the constant capital c is reproduced, not distributed as revenue.
// TotalSocialProductLM = c + (v + s).
type AnnualRevenueAccount struct {
	ID                   AnnualRevenueAccountID `json:"id"`
	NewValueCreatedLM    int64                  `json:"new_value_created_lm"`
	WagesShareLM         int64                  `json:"wages_share_lm"`
	ProfitAndRentShareLM int64                  `json:"profit_and_rent_share_lm"`
	ConstantCapitalLM    int64                  `json:"constant_capital_lm"`
	TotalSocialProductLM int64                  `json:"total_social_product_lm"`
	CreatedAt            time.Time              `json:"created_at"`
}

// ValueAppearanceContrastID identifies a value-appearance-contrast record.
type ValueAppearanceContrastID string

// NewValueAppearanceContrastID returns a fresh 96-bit hex ID.
func NewValueAppearanceContrastID() ValueAppearanceContrastID {
	return ValueAppearanceContrastID(newID())
}

// ValueAppearanceContrast documents, for a given illusion, what market agents
// believe (Surface) against what analysis reveals (Reality).
type ValueAppearanceContrast struct {
	ID         ValueAppearanceContrastID `json:"id"`
	IllusionID string                    `json:"illusion_id"`
	Surface    string                    `json:"surface"`
	Reality    string                    `json:"reality"`
	CreatedAt  time.Time                 `json:"created_at"`
}

// ComputeCostPrice returns the cost-price c + v that appears as the commodity's "real value".
func ComputeCostPrice(constantBP, variableBP int64) int64 {
	return constantBP + variableBP
}

// ComputeActualValue returns the actual value cost-price + profit (= c + v + s).
func ComputeActualValue(costPriceBP, profitBP int64) int64 {
	return costPriceBP + profitBP
}

// ComputeNewValueCreated returns the society-wide new value v + s (wages + profit-and-rent).
func ComputeNewValueCreated(wagesLM, profitAndRentLM int64) int64 {
	return wagesLM + profitAndRentLM
}

// ComputeTotalSocialProduct returns the total social product c + (v + s).
func ComputeTotalSocialProduct(constantLM, newValueLM int64) int64 {
	return constantLM + newValueLM
}
